import { Award, Mail, MapPin, Phone, ShieldCheck } from "lucide-react";

type CandidateProfile = { user: { name: string | null; email: string | null }; headline?: string | null; summary?: string | null; phone?: string | null; location?: string | null; website?: string | null; linkedinUrl?: string | null; githubUrl?: string | null; skills?: Array<{ id: string; name: string; category: string | null; level: number | null }>; certificates?: Array<{ id: string; name: string; issuer: string }> };

export function CandidateProfileView({ profile }: { profile: CandidateProfile }) {
  const skills = profile.skills ?? [];
  const certificates = profile.certificates ?? [];
  const hasDetails = Boolean(profile.headline || profile.summary || profile.phone || profile.location);
  return (
    <div className="space-y-5">
      <section className="rounded-2xl bg-surface-white p-6 shadow-card"><p className="text-sm font-semibold text-primary">Thông tin hồ sơ</p><h1 className="mt-2 text-2xl font-bold text-foreground">{profile.user.name ?? "Ứng viên"}</h1>{profile.headline ? <p className="mt-1 text-sm font-semibold text-primary">{profile.headline}</p> : null}<div className="mt-3 flex flex-wrap gap-3 text-xs font-medium text-text-muted">{profile.user.email ? <span className="flex items-center gap-1"><Mail className="h-3.5 w-3.5" />{profile.user.email}</span> : null}{profile.phone ? <span className="flex items-center gap-1"><Phone className="h-3.5 w-3.5" />{profile.phone}</span> : null}{profile.location ? <span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{profile.location}</span> : null}</div>{profile.summary ? <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-foreground">{profile.summary}</p> : null}{!hasDetails ? <p className="mt-4 rounded-lg bg-surface-low p-4 text-sm text-text-muted">Chưa có thông tin hồ sơ.</p> : null}</section>
      <div className="grid gap-5 md:grid-cols-2"><section className="rounded-2xl bg-surface-white p-6 shadow-card"><h2 className="flex items-center gap-2 font-bold text-foreground"><Award className="h-4 w-4 text-primary" />Kỹ năng</h2>{skills.length === 0 ? <p className="mt-4 text-sm text-text-muted">Chưa có kỹ năng nào.</p> : <ul className="mt-4 flex flex-wrap gap-2">{skills.map((skill) => <li key={skill.id} className="rounded-full bg-surface-container px-3 py-2 text-sm text-foreground"><span className="font-semibold">{skill.name}</span>{skill.category ? <span> · {skill.category}</span> : null}{skill.level ? <span> · {skill.level}/5</span> : null}</li>)}</ul>}</section><section className="rounded-2xl bg-surface-white p-6 shadow-card"><h2 className="flex items-center gap-2 font-bold text-foreground"><ShieldCheck className="h-4 w-4 text-secondary" />Chứng chỉ</h2>{certificates.length === 0 ? <p className="mt-4 text-sm text-text-muted">Chưa có chứng chỉ nào.</p> : <ul className="mt-4 space-y-2">{certificates.map((item) => <li key={item.id} className="rounded-lg bg-surface-low p-3"><p className="font-semibold text-foreground">{item.name}</p><p className="text-xs text-text-muted">{item.issuer}</p></li>)}</ul>}</section></div>
    </div>
  );
}
